name: activemq-io check and unit test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: License check
      run: mvn license:check

    - name: Build with Maven skipTests
      run: mvn clean install -DskipTests

    - name: Style check
      run: mvn checkstyle:check

    - name: Spotbugs check
      run: mvn spotbugs:check

    - name: test after build
      run: mvn test -DfailIfNoTests=false

    - name: package surefire artifacts
      if: failure()
      run: |
        rm -rf artifacts
        mkdir artifacts
        find . -type d -name "*surefire*" -exec cp --parents -R {} artifacts/ \;
        zip -r artifacts.zip artifacts

    - uses: actions/upload-artifact@master
      name: upload surefire-artifacts
      if: failure()
      with:
        name: surefire-artifacts
        path: artifacts.zip
